services:
  - type: web
    name: social-media-app
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build
    preDeployCommand: npx prisma migrate deploy
    startCommand: next start -p $PORT
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
