services:
  - type: web
    name: social-media-app
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /data/uploads
      sizeGB: 10
